---
title: "Vegation Recovery Rate Zonification In PR"
author: 
  - "Israel O. Dilán-Pantojas"
  - "Marcelo Francia-Hinostroza"
  - "Manuel J. La Torre-Poueymirou"
date: "April 9, 2019"
output:
  html_document:
    df_print: paged
  pdf_document: 
    highlight: pygments
---

```{r global_options, message=TRUE, warning=TRUE, include=FALSE, paged.print=TRUE}
knitr::opts_chunk$set(echo = T)
```
## Methods: 

## References:


\pagebreak

## Apendix:
```{r loading_libraries, message=FALSE, warning=FALSE, paged.print=FALSE}
library(ncdf4) # package for netcdf manipulation
library(raster) # package for raster manipulation
library(rgdal) # package for geospatial analysis
library(rasterVis)
library(RColorBrewer)

# library(maptools)
# library(maps)
# library(MODISTools)
# library(mapdata)
library(ggplot2) # packages for plotting
library(chron)
# library(lattice)

```

```{r loading_data}
# load data
setwd("~/Desktop/BigData2Biol/Project_2/Hot_zones")
data <- nc_open(filename = "MOD13Q1.006_250m_aid0001.nc")

n <- names(data$var)

# get longitude and latitude
lon <- ncvar_get(data, "lon")
nlon <- dim(lon)
lat <- ncvar_get(data, "lat")
nlat <- dim(lat)

# get time dimension
time <- ncvar_get(data, "time")
tunits <- ncatt_get(data,"time","units")
nt <- dim(time)

# get ndvi
dname <- n[2]
ndvi_array <- ncvar_get(data,dname)
dlname <- ncatt_get(data,dname,"long_name")
dunits <- ncatt_get(data,dname,"units")
fillvalue <- ncatt_get(data,dname,"_FillValue")

# get Quality
# dname2 <- n[6]
# qual_array <- ncvar_get(data,dname2)
# dlname2 <- ncatt_get(data,dname2,"long_name")
# dunits2 <- ncatt_get(data,dname2,"units")
# fillvalue2 <- ncatt_get(data,dname2,"_FillValue")


# # get LST
# dname <- n[]
# ndvi_array <- ncvar_get(data,dname)
# dlname <- ncatt_get(data,dname,"long_name")
# dunits <- ncatt_get(data,dname,"units")
# fillvalue <- ncatt_get(data,dname,"_FillValue")
# 
# # get evapo
# dname <- "_EVAP"
# ndvi_array <- ncvar_get(data,dname)
# dlname <- ncatt_get(data,dname,"long_name")
# dunits <- ncatt_get(data,dname,"units")
# fillvalue <- ncatt_get(data,dname,"_FillValue")

# get global attributes
title <- ncatt_get(data,0,"title")
institution <- ncatt_get(data,0,"institution")
datasource <- ncatt_get(data,0,"source")
references <- ncatt_get(data,0,"references")
history <- ncatt_get(data,0,"history")
Conventions <- ncatt_get(data,0,"Conventions")

nc_close(data)

# convert time -- split the time units string into fields
tustr <- strsplit(tunits$value, " ")
tdstr <- strsplit(unlist(tustr)[3], "-")
tmonth <- as.integer(unlist(tdstr)[2])
tday <- as.integer(unlist(tdstr)[3])
tyear <- as.integer(unlist(tdstr)[1])

# replace netCDF fill values with NA's
# ndvi_array[ndvi_array==fillvalue$value] <- NA
# NDVIS <- ndvi_array

# identify selected dates
dates <- chron(time,origin=c(tmonth, tday, tyear))
```

<!-- Possible seasonality:  https://verbe039.github.io/BFASTforAEO/ -->

```{r Analysis}
# https://www.earthdatascience.org/courses/earth-analytics/multispectral-remote-sensing-modis/normalized-burn-index-dNBR/
# 
# library(ggplot2)
# library(ggmap)

c <- raster('MOD13Q1.006_250m_aid0001.nc')
s <- stack(c)
levelplot(mean(s), main="All bands")

zonal(c, 'mean')

cellStats(s, mean)

ndvi <- stack('MOD13Q1.006_250m_aid0001.nc', varname = "_250m_16_days_NDVI")
lst <- stack('MOD13Q1.006_250m_aid0001.nc', varname = "_250m_16_days_NDVI")
evap <- stack('MOD13Q1.006_250m_aid0001.nc', varname = "_250m_16_days_NDVI")


avg_ndvi <- cellStats(ndvi,mean)

# convert output array to data.frame
avg_NDVI_HARV <- as.data.frame(avg_NDVI_HARV)


# use colorbrewer which loads with the rasterVis package to generate
# a color ramp of yellow to green
cols <- colorRampPalette(brewer.pal(9,"YlGn"))
# create a level plot - plot

# https://www.neonscience.org/raster-time-series



# png("zonification_plot.png")
# Stack plot for zones
levelplot(ndvi, main="Landsat NDVI stacked over time", col.regions = colorRampPalette(brewer.pal(10,"RdYlGn")))
# dev.off()

# Stack plot for temp
levelplot(lst, main="Landsat LST stacked over time", col.regions = colorRampPalette(brewer.pal(10,"RdYlBu")))

# Stack plot for evap
levelplot(evap, main="Landsat Evapo stacked over time", col.regions = colorRampPalette(brewer.pal(10,"BrBG")))
```

```{r}
for (m in 1:length(dates)) {
  
  par(mfrow=c(1,3))
  ndvi_slice <- ndvi_array[,,m]
  qual_slice <- qual_array[,,m]
  
  r <- raster(t(ndvi_slice), xmn=min(lon), xmx=max(lon), ymn=min(lat), ymx=max(lat), crs=CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs+ towgs84=0,0,0"))
  plot(r, main = dates[m] )
    # turn off scientific notation
  options("scipen" = 100, "digits" = 4)
  # bottom, left, top and right
  #par(mfrow=c(4, 2))
  hist(ndvi_slice,
    col = "springgreen",
    xlab = "NDVI Value")
  mtext(paste("Distribution of MODIS NDVI ", dates[m]),
        outer = TRUE, cex = 1.5)
  hist(qual_slice,
    col = "skyblue",
    xlab = "Quality Value")
  mtext(paste("Distribution of MODIS Quality ", dates[m]),
        outer = TRUE, cex = 1.5)
}
# dev.copy(png,'GIMMS3g_1982_NDVI.png')
# dev.off()
```



